BUG: Workaround "check-jsonschema" caching issue by adding schema to repository
This commit addresses errors reported during the GitHub workflow
associated with `.github/workflows/lint.yml`:

```
Error: schemafile could not be parsed as JSON
SchemaParseError: https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-entry-schema-v1.0.1.json
  in "/home/runner/.cache/pre-commit/reporsapdpi1/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/checker.py", line 56
  >>> return self._schema_loader.get_validator(

  caused by

  FailedFileLoadError: Failed to parse https://raw.githubusercontent.com/Slicer/Slicer/main/Schemas/slicer-extension-catalog-entry-schema-v1.0.1.json
    in "/home/runner/.cache/pre-commit/reporsapdpi1/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/schema_loader/readers.py", line 27
    >>> schema = callback()
```